AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
Globals:
  Function:
    Runtime: python3.14
    Timeout: 10
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  MyPostgresDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      DBName: my_database
      MasterUsername: db_user
      MasterUserPassword: my_secure_password
  
  # DynamoDB
  ChannelsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: String

  # ── SQS Queue ────────────────────────────────────────────────────────
  NotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: notifications
  # ── Lambda Functions ────────────────────────────────────────────────
  # SendMessage:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: SendMessage
  #     CodeUri: src/Messages/SendMessage/
  #     Handler: CreateMessages.lambda_handler
  #     Policies:
  #       - SQSSendMessagePolicy:
  #           QueueName: !GetAtt NotificationQueue.QueueName
  #       - AWSLambdaBasicExecutionRole
  #       - AWSLambdaVPCAccessExecutionRole
  #     Environment:
  #       Variables:
  #         QUEUE_URL: !Ref NotificationQueue
  #     Events:
  #       SendMessage:
  #         Type: Api
  #         Properties:
  #           Path: /api/messages
  #           Method: POST
  #   GetMessages:
  #     Type: AWS::Serverless::Function
  #     Properties:
  #       FunctionName: GetMessages
  #       CodeUri: src/Messages/
  #       Handler: GetAllMessages.lambda_handler
  #       Policies:
  #         - SQSSendMessagePolicy:
  #             QueueName: !GetAtt NotificationQueue.QueueName
  #         - AWSLambdaBasicExecutionRole
  #         - AWSLambdaVPCAccessExecutionRole
  #       Environment:
  #         Variables:
  #           QUEUE_URL: !Ref NotificationQueue
  #       Events:
  #         GetMessages:
  #           Type: Api
  #           Properties:
  #             Path: /api/messages
  #             Method: GET
  #   UpdateMessages:
  #     Type: AWS::Serverless::Function
  #     Properties:
  #       FunctionName: UpdateMessages
  #       CodeUri: src/Messages/
  #       Handler: UpdateMessages.lambda_handler
  #       Policies:
  #         - SQSSendMessagePolicy:
  #             QueueName: !GetAtt NotificationQueue.QueueName
  #         - AWSLambdaBasicExecutionRole
  #         - AWSLambdaVPCAccessExecutionRole
  #       Environment:
  #         Variables:
  #           QUEUE_URL: !Ref NotificationQueue
  #       Events:
  #         UpdateMessages:
  #           Type: Api
  #           Properties:
  #             Path: /api/messages
  #             Method: UPDATE
  #   DeleteMessages:
  #     Type: AWS::Serverless::Function
  #     Properties:
  #       FunctionName: DeleteMessages
  #       CodeUri: src/Messages/
  #       Handler: DeleteMessages.lambda_handler
  #       Policies:
  #         - SQSSendMessagePolicy:
  #             QueueName: !GetAtt NotificationQueue.QueueName
  #         - AWSLambdaBasicExecutionRole
  #         - AWSLambdaVPCAccessExecutionRole
  #       Environment:
  #         Variables:
  #           QUEUE_URL: !Ref NotificationQueue
  #       Events:
  #         DeleteMessages:
  #           Type: Api
  #           Properties:
  #             Path: /api/messages
  #             Method: DELETE
    # GetAllUsers:
    #   Type: AWS::Serverless::Function
    #   Properties:
    #     FunctionName: GetAllUsers
    #     CodeUri: src/Users/
    #     Handler: GetAllUsers.lambda_handler
    #     Policies:
    #       - SQSSendMessagePolicy:
    #           QueueName: !GetAtt NotificationQueue.QueueName
    #       - Version: "2012-10-17"
    #         Statement:
    #           - Effect: Allow
    #             Action:
    #               - rds-db:connect
    #             Resource:
    #               - arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:cluster-ABCDEFGHIJKLMN/users
    #     Environment:
    #       Variables:
    #         QUEUE_URL: !Ref NotificationQueue
    #     Events:
    #       GetAllUsers:
    #         Type: Api
    #         Properties:
    #           Path: /api/users
    #           Method: GET
    # GetOneUsers:
    #   Type: AWS::Serverless::Function
    #   Properties:
    #     FunctionName: GetOneUsers
    #     CodeUri: src/Users/
    #     Handler: GetOneUsers.lambda_handler
    #     Policies:
    #       - SQSSendMessagePolicy:
    #           QueueName: !GetAtt NotificationQueue.QueueName
    #       - Version: "2012-10-17"
    #         Statement:
    #           - Effect: Allow
    #             Action:
    #               - rds-db:connect
    #             Resource:
    #               - arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:cluster-ABCDEFGHIJKLMN/users
    #     Environment:
    #       Variables:
    #         QUEUE_URL: !Ref NotificationQueue
    #     Events:
    #       GetOneUsers:
    #         Type: Api
    #         Properties:
    #           Path: /api/users
    #           Method: GET
    # SignUpUsers:
    #   Type: AWS::Serverless::Function
    #   Properties:
    #     FunctionName: SignUpUsers
    #     CodeUri: src/Users/
    #     Handler: SignUpUsers.lambda_handler
    #     Policies:
    #       - SQSSendMessagePolicy:
    #           QueueName: !GetAtt NotificationQueue.QueueName
    #       - Version: "2012-10-17"
    #         Statement:
    #           - Effect: Allow
    #             Action:
    #               - rds-db:connect
    #             Resource:
    #               - arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:cluster-ABCDEFGHIJKLMN/users
    #     Environment:
    #       Variables:
    #         QUEUE_URL: !Ref NotificationQueue
    #     Events:
    #       SignUpUsers:
    #         Type: Api
    #         Properties:
    #           Path: /api/users
    #           Method: POST
    # UpdateUsers:
    #   Type: AWS::Serverless::Function
    #   Properties:
    #     FunctionName: UpdateUsers
    #     CodeUri: src/Users/
    #     Handler: UpdateUsers.lambda_handler
    #     Policies:
    #       - SQSSendMessagePolicy:
    #           QueueName: !GetAtt NotificationQueue.QueueName
    #       - Version: "2012-10-17"
    #         Statement:
    #           - Effect: Allow
    #             Action:
    #               - rds-db:connect
    #             Resource:
    #               - arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:cluster-ABCDEFGHIJKLMN/users
    #     Environment:
    #       Variables:
    #         QUEUE_URL: !Ref NotificationQueue
    #     Events:
    #       UpdateUsers:
    #         Type: Api
    #         Properties:
    #           Path: /api/users
    #           Method: UPDATE
    # DeleteUsers:
    #   Type: AWS::Serverless::Function
    #   Properties:
    #     FunctionName: DeleteUsers
    #     CodeUri: src/Users/
    #     Handler: DeleteUsers.lambda_handler
    #     Policies:
    #       - SQSSendMessagePolicy:
    #           QueueName: !GetAtt NotificationQueue.QueueName
    #       - Version: "2012-10-17"
    #         Statement:
    #           - Effect: Allow
    #             Action:
    #               - rds-db:connect
    #             Resource:
    #               - arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:cluster-ABCDEFGHIJKLMN/users
    #     Environment:
    #       Variables:
    #         QUEUE_URL: !Ref NotificationQueue
    #     Events:
    #       DeleteUsers:
    #         Type: Api
    #         Properties:
    #           Path: /api/users
    #           Method: DELETE
  # NotifyDirectorFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: mod05-notify-director-consumer
  #     CodeUri: ex5-2/notify_director/
  #     Handler: app.lambda_handler
  #     Events:
  #       NotificationQueueEvent:
  #         Type: SQS
  #         Properties:
  #           Queue: !GetAtt NotificationQueue.Arn
  #           BatchSize: 10

#Outputs:
  # ApiUrl:
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  # NotificationQueueUrl:
  #   Value: !Ref NotificationQueue
  # NotificationQueueArn:
  #   Value: !GetAtt NotificationQueue.Arn
  # ProducerFunctionName:
  #   Value: !Ref SignUpForAuditionFunction

  # ConsumerFunctionName:
  #   Value: !Ref NotifyDirectorFunction