AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
Globals:
  Function:
    Runtime: python3.14
    Timeout: 10
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions
      VpcId: vpc-0097d5ecedf0fc0c5
  MyPostgresDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      DBName: my_database
      MasterUsername: db_user
      MasterUserPassword: my_secure_password
  
  # DynamoDB
  ChannelsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: String

  # ── SQS Queue ────────────────────────────────────────────────────────
  NotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: notifications
  # ── Lambda Functions ────────────────────────────────────────────────

  #USER LAMBDA

# GetOneUsers:
#   Type: AWS::Serverless::Function
#   Properties:
#     FunctionName: GetOneUsers
#     CodeUri: src/Users/
#     Handler: GetOneUsers.lambda_handler
#     Policies:
#       - AWSLambdaBasicExecutionRole
#     Environment:
#       Variables:
#         DB_HOST: !GetAtt MyPostgresDB.Endpoint.Address
#         DB_PORT: !GetAtt MyPostgresDB.Endpoint.Port
#         DB_NAME: my_database
#         DB_USER: db_user
#         DB_PASSWORD: my_secure_password
#     Events:
#       GetOneUsers:
#         Type: Api
#         Properties:
#           Path: /api/users/{user_id}
#           Method: GET
  GetAllUsers:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetAllUsers
      CodeUri: src/Users/
      Handler: GetAllUsers.lambda_handler
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - subnet-000bbe0ea15d9fbcb
          - subnet-0ff2a9217a5a24230
          - subnet-013ab40ccdb082226
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          DB_HOST: !GetAtt MyPostgresDB.Endpoint.Address
          DB_PORT: !GetAtt MyPostgresDB.Endpoint.Port
          DB_NAME: my_database
          DB_USER: db_user
          DB_PASSWORD: my_secure_password
      Events:
        GetAllUsers:
          Type: Api
          Properties:
            Path: /api/users
            Method: GET
  SignUpUsers:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SignUpUsers
      CodeUri: src/
      Handler: Users.SignUpUser.lambda_handler
      Timeout: 20
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - subnet-000bbe0ea15d9fbcb
          - subnet-0ff2a9217a5a24230
          - subnet-013ab40ccdb082226
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          DB_HOST: !GetAtt MyPostgresDB.Endpoint.Address
          DB_PORT: !GetAtt MyPostgresDB.Endpoint.Port
          DB_NAME: my_database
          DB_USER: db_user
          DB_PASSWORD: my_secure_password
      Events:
        SignUpUsers:
          Type: Api
          Properties:
            Path: /api/users/create
            Method: POST
  UpdateUsers:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UpdateUsers
      CodeUri: src/Users/
      Handler: UpdateUser.lambda_handler
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - subnet-000bbe0ea15d9fbcb
          - subnet-0ff2a9217a5a24230
          - subnet-013ab40ccdb082226
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          DB_HOST: !GetAtt MyPostgresDB.Endpoint.Address
          DB_PORT: !GetAtt MyPostgresDB.Endpoint.Port
          DB_NAME: my_database
          DB_USER: db_user
          DB_PASSWORD: my_secure_password
      Events:
        UpdateUsers:
          Type: Api
          Properties:
            Path: /api/users
            Method: UPDATE
  DeleteUsers:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DeleteUsers
      CodeUri: src/Users/
      Handler: DeleteUser.lambda_handler
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - subnet-000bbe0ea15d9fbcb
          - subnet-0ff2a9217a5a24230
          - subnet-013ab40ccdb082226
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          DB_HOST: !GetAtt MyPostgresDB.Endpoint.Address
          DB_PORT: !GetAtt MyPostgresDB.Endpoint.Port
          DB_NAME: my_database
          DB_USER: db_user
          DB_PASSWORD: my_secure_password
      Events:
        DeleteUsers:
          Type: Api
          Properties:
            Path: /api/users/{user_id}
            Method: DELETE
  Login:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Login
      CodeUri: src/
      Handler: Users.Login.lambda_handler
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - subnet-000bbe0ea15d9fbcb
          - subnet-0ff2a9217a5a24230
          - subnet-013ab40ccdb082226
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          DB_HOST: !GetAtt MyPostgresDB.Endpoint.Address
          DB_PORT: !GetAtt MyPostgresDB.Endpoint.Port
          DB_NAME: my_database
          DB_USER: db_user
          DB_PASSWORD: my_secure_password
      Events:
        Login:
          Type: Api
          Properties:
            Path: /api/users
            Method: POST
            
    #MESSAGE LAMBDA
    
  # SendMessage:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: SendMessage
  #     CodeUri: src/Messages/
  #     Handler: CreateMessages.lambda_handler
  #     Policies:
  #       - AWSLambdaBasicExecutionRole
  #     Environment:
  #       Variables:
  #         QUEUE_URL: !Ref NotificationQueue
  #     Events:
  #       SendMessage:
  #         Type: Api
  #         Properties:
  #           Path: /api/messages
  #           Method: POST
  #   GetMessages:
  #     Type: AWS::Serverless::Function
  #     Properties:
  #       FunctionName: GetMessages
  #       CodeUri: src/Messages/
  #       Handler: GetAllMessages.lambda_handler
  #       Policies:
  #         - AWSLambdaBasicExecutionRole
  #       Environment:
  #         Variables:
  #           QUEUE_URL: !Ref NotificationQueue
  #       Events:
  #         GetMessages:
  #           Type: Api
  #           Properties:
  #             Path: /api/messages
  #             Method: GET
  #   UpdateMessages:
  #     Type: AWS::Serverless::Function
  #     Properties:
  #       FunctionName: UpdateMessages
  #       CodeUri: src/Messages/
  #       Handler: UpdateMessages.lambda_handler
  #       Policies:
  #         - AWSLambdaBasicExecutionRole
  #       Environment:
  #         Variables:
  #           QUEUE_URL: !Ref NotificationQueue
  #       Events:
  #         UpdateMessages:
  #           Type: Api
  #           Properties:
  #             Path: /api/messages
  #             Method: UPDATE
  #   DeleteMessages:
  #     Type: AWS::Serverless::Function
  #     Properties:
  #       FunctionName: DeleteMessages
  #       CodeUri: src/Messages/
  #       Handler: DeleteMessages.lambda_handler
  #       Policies:
  #         - AWSLambdaBasicExecutionRole
  #       Environment:
  #         Variables:
  #           QUEUE_URL: !Ref NotificationQueue
  #       Events:
  #         DeleteMessages:
  #           Type: Api
  #           Properties:
  #             Path: /api/messages
  #             Method: DELETE
  # NotifyDirectorFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: mod05-notify-director-consumer
  #     CodeUri: ex5-2/notify_director/
  #     Handler: app.lambda_handler
  #     Events:
  #       NotificationQueueEvent:
  #         Type: SQS
  #         Properties:
  #           Queue: !GetAtt NotificationQueue.Arn
  #           BatchSize: 10
Outputs:
  ApiUrl:
    Description: API Gateway endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  DatabaseEndpoint:
    Description: PostgreSQL database endpoint
    Value: !GetAtt MyPostgresDB.Endpoint.Address
  DatabasePort:
    Description: PostgreSQL database port
    Value: !GetAtt MyPostgresDB.Endpoint.Port
  DatabaseName:
    Description: PostgreSQL database name
    Value: my_database
  NotificationQueueUrl:
    Description: SQS notification queue URL
    Value: !Ref NotificationQueue
  NotificationQueueArn:
    Description: SQS notification queue ARN
    Value: !GetAtt NotificationQueue.Arn